# Generated by Django 3.0.8 on 2020-08-18 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200818_1432'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Work_detaiil',
            new_name='Work_detail',
        ),
    ]
